{% set name = "BitMagic" %}
{% set version = "7.13.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tlk00/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3a45e2f11396b09f963573af299d9ce03b6d100357d317c817cd91cca4ba84c4

build:
  number: 0

test:
  commands:
    - test -e ${PREFIX}/include/bitmagic/bm.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\bitmagic\bm.h (exit 1)  # [win]

about:
  home: https://github.com/tlk00/BitMagic
  summary: BitMagic is a general data science components library
  description: BitMagic is a general data science components library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DerThorsten
