{% set name = "BitMagic" %}
{% set version = "7.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tlk00/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5e59507a01a8295bb57aebcf557a4a25b992244736f7924300cdb9635f1b2780

build:
  number: 1

test:
  commands:
    - test -e ${PREFIX}/include/bitmagic/bm.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\bitmagic\bm.h (exit 1)  # [win]

about:
  home: https://github.com/tlk00/BitMagic
  summary: 'BitMagic is a general data science components library'
  description: BitMagic is a general data science components library
  license: 'Apache-2.0'
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DerThorsten
