{% set name = "BitMagic" %}
{% set version = "8.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tlk00/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9ef069c4b07da69f7a357eb3e8adf83c55cdd05deb03d52326ca13beb5896cb1

build:
  number: 0

test:
  commands:
    - test -e ${PREFIX}/include/bitmagic/bm.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\bitmagic\bm.h (exit 1)  # [win]

about:
  home: https://github.com/tlk00/BitMagic
  summary: BitMagic is a general data science components library
  description: BitMagic is a general data science components library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DerThorsten
